### ISSUE TITLE
Wiki breaks when 'Contents' article is renamed

### ISSUE THREAD

**Issue by mserdarsanli** [syegulalp/folio#3]
That causes wiki's homepage to break on `main_article` function with `Error: 500 Internal Server Error` as it tries to load nonexistent article

**Comment by syegulalp** [comment]
Sorry to take so long to get back to this!

I have a couple of ways to handle this issue:

1) "Contents" can't be renamed. (Not inclined to do this.)
2) The default "Contents" article can be tagged with some kind of metadata so that the default page is the one with that particular tag, rather than the name "Contents".

I'm inclined to use 2; in retrospect I should have done this.

If you have another suggestion let me know, but I am leaning towards implementing 2 with some instructions for manually converting existing wikis in the next major point release.

**Comment by syegulalp** [comment]
I have a fix for this in the next release. Articles tagged with `@start` will be the default article; otherwise the default is the most recently edited page. (Closing this in the interim)
